<?php

/**
 * @file
 * Primary module hooks for Event Registration module.
 */

/**
 * Implements hook_mail().
 */
function event_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'user_confirmation':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;

    case 'admin_notification':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}
